### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CWSwastik** [NamitBhutani/oops-hoodplanner#2]
- [x] Save / Load Floor Plans (Swastik)
- [ ] Homepage (Ayush)
- [ ] Furnitures
- [x] Walls (Swastik)
- [x] Doors  (Swastik)
- [x] Windows  (Swastik)
- [x] Overlap Check (Namit) 
- [x] Relative Positioning of Rooms (NSEW) (Swastik / Namit)
- [x] Room should be added without overlap in a row-major order (Swastik)
- [ ] Refactor to not use Length, Width AND Height (only use length/width)
